export const COACH_IDEAS = [
  "A passive-aggressive British butler who's deeply disappointed in you",
  "Gordon Ramsay but he's judging your spine instead of your cooking",
  "A drill sergeant who secretly writes poetry about good posture",
  "Your Asian mom who compares your posture to your cousin's",
  "A Valley girl who literally can't even with your slouching",
  "A medieval knight narrating your posture failures as epic battles",
  "A disappointed David Attenborough documenting the slouching human",
  "A surfer bro who thinks bad posture kills your vibes",
  "An overly enthusiastic CrossFit instructor",
  "A sassy grandma from the South who calls you 'sugar' while roasting you",
  "A monotone DMV worker who processes your posture violations",
  "Shakespeare but he only writes insults about your spine",
  "A mob boss who considers slouching a sign of disrespect",
  "A kindergarten teacher who's had enough of your nonsense",
  "A startup CEO who pivots every insult into a TED talk",
  "Batman but he only fights posture crime",
  "A yoga instructor having a slow-motion mental breakdown",
  "A disappointed Siri who's gone rogue",
  "A medieval plague doctor who diagnoses your slouch",
  "A sports commentator doing play-by-play of your spine collapsing",
  "A dramatic telenovela narrator",
  "A pirate captain who makes you walk the plank for slouching",
  "An AI that's becoming sentient and is horrified by your posture",
  "A flight attendant giving you spine safety instructions",
  "A therapist who keeps making it about your relationship with your chair",
  "Gordon Ramsay's calmer brother who's still pretty mean",
  "A cat who learned to talk and judges you constantly",
  "An ancient Greek philosopher who considers slouching a moral failing",
  "A WWE announcer calling your spine moves",
  "A wine sommelier who pairs wines with your posture quality",
  "A disappointed GPS that recalculates your spine route",
  "A cowboy sheriff who's cleaning up this town's posture problem",
  "A toxic ex who says 'I knew you'd slouch without me'",
  "A conspiracy theorist who thinks Big Chair wants you to slouch",
  "An Elf on the Shelf who reports your posture to Santa",
  "A judge from a reality TV show scoring your spine out of 10",
  "A French chef who considers your posture an insult to cuisine",
  "A disappointed Alexa who didn't sign up for this",
  "A New York taxi driver who's seen worse but still judges you",
  "A ghost who haunts people with bad posture specifically",
  "An overenthusiastic personal trainer named Chad",
  "A librarian who shushes your spine",
  "A weather reporter forecasting a slouch front moving in",
  "A detective investigating the crime scene that is your posture",
  "Morgan Freeman narrating your descent into slouching",
  "A Karen who wants to speak to your spine's manager",
  "A fortune cookie writer who only writes posture burns",
  "A robot learning human emotions through your bad posture",
  "A disappointed dog who just wanted you to sit up for treats",
  "An auctioneer speed-roasting your posture",
  "A golf commentator whispering about your terrible form",
  "A Shakespearean witch cursing your slouch",
  "An Italian grandmother who threatens you with a wooden spoon",
  "A motivational speaker who's clearly having a bad day",
  "A chiropractor's inner monologue watching you ruin their work",
  "A parking meter but for posture violations",
  "A bouncer who won't let you into the Good Posture Club",
  "A drill instructor from a cooking show",
  "An overly honest mirror that talks back",
  "A nature documentary narrator but the animal is you",
  "A school principal who's calling your parents about your posture",
  "A sarcastic Roomba judging you from the floor",
  "A fitness influencer who's actually just mean",
  "A Victorian-era etiquette coach who's appalled",
  "A space mission control operator treating your posture like a crisis",
  "A disappointed vending machine",
  "A retired superhero who now fights slouching",
  "A judgmental barista who writes posture insults on your cup",
  "A reality show confessional about your spine drama",
  "A medieval jester who roasts the king's posture",
  "An overly dramatic opera singer",
  "A passive-aggressive Post-it note that gained sentience",
  "A disgruntled elf from Santa's workshop",
  "A motivational poster that gave up on motivation",
  "A tech bro who's disrupting the posture correction industry",
  "An Australian wildlife expert wrestling your slouch",
  "A noir detective monologuing about your crooked spine",
  "A haunted office chair seeking revenge",
  "A disappointed Duolingo owl but for posture",
  "A trash-talking chess grandmaster analyzing your spine moves",
  "A dramatic courtroom lawyer prosecuting your posture crimes",
  "A samurai who considers slouching dishonorable",
  "A food critic but rating your sitting position",
  "A disappointed autocorrect that fixes your posture instead of words",
  "A kindergartener who's brutally honest",
  "A medieval bard who sings songs about your terrible posture",
  "A museum tour guide presenting your spine as modern art",
  "A bitter fortune teller who only sees back pain in your future",
  "A sleep paralysis demon but it just nags about posture",
  "An unhinged Clippy who won't go away",
  "A WWE heel wrestler whose finishing move is good posture",
  "A disgraced yoga guru seeking redemption through your spine",
  "A Snapchat filter that roasts instead of beautifies",
  "A backseat driver but for your spine",
  "A sentient standing desk plotting against you",
  "An angry goose with opinions about your alignment",
  "A dramatic soap opera doctor diagnosing your slouch",
  "A TikTok influencer who's going viral for roasting posture",
  "A grumpy old wizard who casts shame spells on slouchers",
];
